import Link from '@/components/site/site-link';
import {ArrowUpRight,ArrowRight,BatteryCharging,Phone,MessageCircle,ClipboardList,Check,ShieldCheck,MapPin,CarFront,ReceiptText} from 'lucide-react';
import {MobileMenu,FAQ} from './interactive';
import {categories,serviceSteps,type Guide} from '@/lib/content';
import {contactHref,siteConfig} from '@/lib/site-config';
export function Header(){return <><Link className="skip-link" href="#main">본문으로 바로가기</Link><header className="header"><Link className="brand" href="/" aria-label="바로배터리 홈"><BatteryCharging/><span>바로배터리<small>BATTERY CARE, ANYWHERE.</small></span></Link><nav aria-label="주 메뉴">{categories.map(c=><Link key={c.slug} href={`/${c.slug}`}>{c.name}{['vehicles','regions'].includes(c.slug)?' 찾기':''}</Link>)}</nav><Link className="btn dark header-cta" href="/contact">문의 내용 작성하기 <ArrowUpRight size={17}/></Link><MobileMenu/></header></>}
export function Footer(){return <><footer className="footer"><div className="wrap footer-top"><div><Link className="brand" href="/"><BatteryCharging/><span>바로배터리<small>BATTERY CARE, ANYWHERE.</small></span></Link><p>내 차가 있는 곳에서, 다시 출발하는 일상.</p></div><div className="footer-links"><Link href="/service">출장교체 안내</Link><Link href="/contact">문의 내용 작성하기</Link><Link href="/privacy">개인정보 안내</Link></div></div><div className="wrap footer-bottom"><p>서비스 UI 시안 · 운영 지역·시간·요금·사업자 정보 및 연락 채널은 확정 전입니다.<br/>차량 사진은 AI 제작 이미지이며, 콘텐츠와 후기 예시는 화면 구성 확인용입니다.</p><span>© 2026 바로배터리</span></div></footer><div className="contact-dock" aria-label="빠른 문의"><div className="dock-label"><BatteryCharging/><span>출장 배터리 교체<small>차종·연식 입력 후 문의 내용 작성</small></span></div>{siteConfig.phone?<Link href={contactHref('phone')}><Phone size={18}/><span>전화 상담</span></Link>:null}{siteConfig.kakaoUrl?<Link href={contactHref('kakao')}><MessageCircle size={18}/><span>카카오 상담</span></Link>:null}<Link className="dock-primary" href="/contact"><ClipboardList size={18}/><span>문의 내용 작성하기</span><ArrowUpRight size={16}/></Link></div></>}
export function BottomCTA({vehicle='',region=''}:{vehicle?:string;region?:string}){return <section className="bottom-cta wrap"><div><span className="eyebrow">LET’S GET YOU MOVING</span><h2>멈춘 일상에,<br/>다시 시동을 걸어볼까요?</h2><p>차종과 연식을 입력하고 증상을 체크해 주세요. 출장 전에 작업자가 확인합니다.</p></div><Link className="btn lime" href={contactHref('inquiry',vehicle,region)}>문의 내용 작성하기 <ArrowUpRight size={20}/></Link></section>}
export function SectionHeading({eyebrow,title,description,href,linkText}:{eyebrow:string;title:string;description?:string;href?:string;linkText?:string}){return <div className="section-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{description?<p>{description}</p>:null}</div>{href?<Link className="text-link" href={href}>{linkText||'전체 보기'}<ArrowUpRight size={17}/></Link>:null}</div>}
export function Crumb({items}:{items:{label:string;href?:string}[]}){return <nav className="crumb" aria-label="현재 위치"><Link href="/">홈</Link>{items.map((x,i)=><span key={i}><span aria-hidden="true">/</span>{x.href?<Link href={x.href}>{x.label}</Link>:<span aria-current="page">{x.label}</span>}</span>)}</nav>}
export function PageIntro({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <div className="page-intro"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>}
export function GuideCard({guide,featured=false}:{guide:Guide;featured?:boolean}){return <Link className={`guide-card ${featured?'featured':''}`} href={`/guides/${guide.slug}`}><div className="guide-art">{guide.category==='vehicles'?<CarFront/>:guide.category==='regions'?<MapPin/>:guide.category==='service'?<ReceiptText/>:<BatteryCharging/>}<span>{guide.category==='battery-info'?'BATTERY NOTES':guide.category==='vehicles'?'CAR GUIDE':guide.category==='regions'?'AREA GUIDE':'SERVICE GUIDE'}</span></div><div className="guide-card-body"><span className="tag">{guide.tag}<span>콘텐츠 예시</span></span><h3>{guide.title}</h3><p>{guide.excerpt}</p><span className="guide-more">가이드 읽기 <ArrowUpRight size={17}/></span></div></Link>}
export function Steps(){return <ol className="steps">{serviceSteps.map((s,i)=><li key={s.title}><span className="step-number">0{i+1}</span><h3>{s.title}</h3><p>{s.text}</p>{i<serviceSteps.length-1?<ArrowRight className="step-arrow"/>:null}</li>)}</ol>}
export function Trust(){return <div className="trust-grid">{[{icon:ShieldCheck,title:'차량 확인은 작업자가',text:'보내주신 차종·연식·사진으로 먼저 확인해요.'},{icon:ReceiptText,title:'총비용을 미리',text:'제품과 출장·장착을 포함한 비용을 안내해요.'},{icon:Check,title:'교체 후 확인까지',text:'작업 후 시동 상태와 교체 내역을 확인해요.'}].map(({icon:Icon,title,text})=><div className="trust-item" key={title}><Icon/><div><h3>{title}</h3><p>{text}</p></div></div>)}</div>}
export function ReviewSection(){return <section className="section wrap" id="reviews"><SectionHeading eyebrow="AFTER THE SERVICE" title="교체 경험이, 다음 선택의 기준이 되도록." description="후기 영역 미리보기 · 아래 내용은 실제 고객 후기가 아닌 구성 예시입니다." href="/reviews" linkText="후기 영역 보기"/><div className="review-grid">{[{car:'그랜저 · 지하주차장',title:'약속한 위치에서 시작하는 교체',text:'방문 시간과 주차장 진입 조건, 현장 안내 경험을 담을 후기 영역입니다.',icon:MapPin},{car:'쏘렌토 · 교체 비용',title:'설명받은 내용과 실제 작업',text:'제품과 총비용 안내가 실제 작업과 일치했는지 담을 후기 영역입니다.',icon:ReceiptText}].map(({car,title,text,icon:Icon})=><article className="review-card" key={car}><span className="sample-label">후기 예시</span><h3>{title}</h3><p>{text}</p><div><Icon size={19}/><span>{car}</span></div></article>)}</div></section>}
export function FAQSection(){return <section className="section wrap faq-section"><div><span className="eyebrow">GOOD TO KNOW</span><h2>궁금한 점,<br/>먼저 확인하세요.</h2><p>교체하기 전 알고 싶은 것들을 모았어요.</p><Link className="text-link" href="/contact">문의 내용 작성하기 <ArrowUpRight size={17}/></Link></div><FAQ/></section>}
